use crate::cpu::Cpu;

use super::operations::targets::ArithmeticTarget8Bit;

use super::operations::bit::Bit;
use super::operations::res::Res;
use super::operations::rl::Rl;
use super::operations::rlc::Rlc;
use super::operations::rr::Rr;
use super::operations::rrc::Rrc;
use super::operations::set::Set;
use super::operations::sla::Sla;
use super::operations::sra::Sra;
use super::operations::srl::Srl;
use super::operations::swap::Swap;

pub fn run_extended_operation(cpu: &mut Cpu, op_code: u8) {
    match op_code {
        0x00 => cpu.run_operation(Rlc::new(ArithmeticTarget8Bit::B), 8),
        0x01 => cpu.run_operation(Rlc::new(ArithmeticTarget8Bit::C), 8),
        0x02 => cpu.run_operation(Rlc::new(ArithmeticTarget8Bit::D), 8),
        0x03 => cpu.run_operation(Rlc::new(ArithmeticTarget8Bit::E), 8),
        0x04 => cpu.run_operation(Rlc::new(ArithmeticTarget8Bit::H), 8),
        0x05 => cpu.run_operation(Rlc::new(ArithmeticTarget8Bit::L), 8),
        0x06 => cpu.run_operation(Rlc::new(ArithmeticTarget8Bit::HLAddr), 16),
        0x07 => cpu.run_operation(Rlc::new(ArithmeticTarget8Bit::A), 8),
        0x08 => cpu.run_operation(Rrc::new(ArithmeticTarget8Bit::B), 8),
        0x09 => cpu.run_operation(Rrc::new(ArithmeticTarget8Bit::C), 8),
        0x0A => cpu.run_operation(Rrc::new(ArithmeticTarget8Bit::D), 8),
        0x0B => cpu.run_operation(Rrc::new(ArithmeticTarget8Bit::E), 8),
        0x0C => cpu.run_operation(Rrc::new(ArithmeticTarget8Bit::H), 8),
        0x0D => cpu.run_operation(Rrc::new(ArithmeticTarget8Bit::L), 8),
        0x0E => cpu.run_operation(Rrc::new(ArithmeticTarget8Bit::HLAddr), 16),
        0x0F => cpu.run_operation(Rrc::new(ArithmeticTarget8Bit::A), 8),

        0x10 => cpu.run_operation(Rl::new(ArithmeticTarget8Bit::B), 8),
        0x11 => cpu.run_operation(Rl::new(ArithmeticTarget8Bit::C), 8),
        0x12 => cpu.run_operation(Rl::new(ArithmeticTarget8Bit::D), 8),
        0x13 => cpu.run_operation(Rl::new(ArithmeticTarget8Bit::E), 8),
        0x14 => cpu.run_operation(Rl::new(ArithmeticTarget8Bit::H), 8),
        0x15 => cpu.run_operation(Rl::new(ArithmeticTarget8Bit::L), 8),
        0x16 => cpu.run_operation(Rl::new(ArithmeticTarget8Bit::HLAddr), 16),
        0x17 => cpu.run_operation(Rl::new(ArithmeticTarget8Bit::A), 8),
        0x18 => cpu.run_operation(Rr::new(ArithmeticTarget8Bit::B), 8),
        0x19 => cpu.run_operation(Rr::new(ArithmeticTarget8Bit::C), 8),
        0x1A => cpu.run_operation(Rr::new(ArithmeticTarget8Bit::D), 8),
        0x1B => cpu.run_operation(Rr::new(ArithmeticTarget8Bit::E), 8),
        0x1C => cpu.run_operation(Rr::new(ArithmeticTarget8Bit::H), 8),
        0x1D => cpu.run_operation(Rr::new(ArithmeticTarget8Bit::L), 8),
        0x1E => cpu.run_operation(Rr::new(ArithmeticTarget8Bit::HLAddr), 16),
        0x1F => cpu.run_operation(Rr::new(ArithmeticTarget8Bit::A), 8),

        0x20 => cpu.run_operation(Sla::new(ArithmeticTarget8Bit::B), 8),
        0x21 => cpu.run_operation(Sla::new(ArithmeticTarget8Bit::C), 8),
        0x22 => cpu.run_operation(Sla::new(ArithmeticTarget8Bit::D), 8),
        0x23 => cpu.run_operation(Sla::new(ArithmeticTarget8Bit::E), 8),
        0x24 => cpu.run_operation(Sla::new(ArithmeticTarget8Bit::H), 8),
        0x25 => cpu.run_operation(Sla::new(ArithmeticTarget8Bit::L), 8),
        0x26 => cpu.run_operation(Sla::new(ArithmeticTarget8Bit::HLAddr), 16),
        0x27 => cpu.run_operation(Sla::new(ArithmeticTarget8Bit::A), 8),
        0x28 => cpu.run_operation(Sra::new(ArithmeticTarget8Bit::B), 8),
        0x29 => cpu.run_operation(Sra::new(ArithmeticTarget8Bit::C), 8),
        0x2A => cpu.run_operation(Sra::new(ArithmeticTarget8Bit::D), 8),
        0x2B => cpu.run_operation(Sra::new(ArithmeticTarget8Bit::E), 8),
        0x2C => cpu.run_operation(Sra::new(ArithmeticTarget8Bit::H), 8),
        0x2D => cpu.run_operation(Sra::new(ArithmeticTarget8Bit::L), 8),
        0x2E => cpu.run_operation(Sra::new(ArithmeticTarget8Bit::HLAddr), 16),
        0x2F => cpu.run_operation(Sra::new(ArithmeticTarget8Bit::A), 8),

        0x30 => cpu.run_operation(Swap::new(ArithmeticTarget8Bit::B), 8),
        0x31 => cpu.run_operation(Swap::new(ArithmeticTarget8Bit::C), 8),
        0x32 => cpu.run_operation(Swap::new(ArithmeticTarget8Bit::D), 8),
        0x33 => cpu.run_operation(Swap::new(ArithmeticTarget8Bit::E), 8),
        0x34 => cpu.run_operation(Swap::new(ArithmeticTarget8Bit::H), 8),
        0x35 => cpu.run_operation(Swap::new(ArithmeticTarget8Bit::L), 8),
        0x36 => cpu.run_operation(Swap::new(ArithmeticTarget8Bit::HLAddr), 16),
        0x37 => cpu.run_operation(Swap::new(ArithmeticTarget8Bit::A), 8),
        0x38 => cpu.run_operation(Srl::new(ArithmeticTarget8Bit::B), 8),
        0x39 => cpu.run_operation(Srl::new(ArithmeticTarget8Bit::C), 8),
        0x3A => cpu.run_operation(Srl::new(ArithmeticTarget8Bit::D), 8),
        0x3B => cpu.run_operation(Srl::new(ArithmeticTarget8Bit::E), 8),
        0x3C => cpu.run_operation(Srl::new(ArithmeticTarget8Bit::H), 8),
        0x3D => cpu.run_operation(Srl::new(ArithmeticTarget8Bit::L), 8),
        0x3E => cpu.run_operation(Srl::new(ArithmeticTarget8Bit::HLAddr), 16),
        0x3F => cpu.run_operation(Srl::new(ArithmeticTarget8Bit::A), 8),

        0x40 => cpu.run_operation(Bit::new(0, ArithmeticTarget8Bit::B), 8),
        0x41 => cpu.run_operation(Bit::new(0, ArithmeticTarget8Bit::C), 8),
        0x42 => cpu.run_operation(Bit::new(0, ArithmeticTarget8Bit::D), 8),
        0x43 => cpu.run_operation(Bit::new(0, ArithmeticTarget8Bit::E), 8),
        0x44 => cpu.run_operation(Bit::new(0, ArithmeticTarget8Bit::H), 8),
        0x45 => cpu.run_operation(Bit::new(0, ArithmeticTarget8Bit::L), 8),
        0x46 => cpu.run_operation(Bit::new(0, ArithmeticTarget8Bit::HLAddr), 16),
        0x47 => cpu.run_operation(Bit::new(0, ArithmeticTarget8Bit::A), 8),
        0x48 => cpu.run_operation(Bit::new(1, ArithmeticTarget8Bit::B), 8),
        0x49 => cpu.run_operation(Bit::new(1, ArithmeticTarget8Bit::C), 8),
        0x4A => cpu.run_operation(Bit::new(1, ArithmeticTarget8Bit::D), 8),
        0x4B => cpu.run_operation(Bit::new(1, ArithmeticTarget8Bit::E), 8),
        0x4C => cpu.run_operation(Bit::new(1, ArithmeticTarget8Bit::H), 8),
        0x4D => cpu.run_operation(Bit::new(1, ArithmeticTarget8Bit::L), 8),
        0x4E => cpu.run_operation(Bit::new(1, ArithmeticTarget8Bit::HLAddr), 16),
        0x4F => cpu.run_operation(Bit::new(1, ArithmeticTarget8Bit::A), 8),

        0x50 => cpu.run_operation(Bit::new(2, ArithmeticTarget8Bit::B), 8),
        0x51 => cpu.run_operation(Bit::new(2, ArithmeticTarget8Bit::C), 8),
        0x52 => cpu.run_operation(Bit::new(2, ArithmeticTarget8Bit::D), 8),
        0x53 => cpu.run_operation(Bit::new(2, ArithmeticTarget8Bit::E), 8),
        0x54 => cpu.run_operation(Bit::new(2, ArithmeticTarget8Bit::H), 8),
        0x55 => cpu.run_operation(Bit::new(2, ArithmeticTarget8Bit::L), 8),
        0x56 => cpu.run_operation(Bit::new(2, ArithmeticTarget8Bit::HLAddr), 16),
        0x57 => cpu.run_operation(Bit::new(2, ArithmeticTarget8Bit::A), 8),
        0x58 => cpu.run_operation(Bit::new(3, ArithmeticTarget8Bit::B), 8),
        0x59 => cpu.run_operation(Bit::new(3, ArithmeticTarget8Bit::C), 8),
        0x5A => cpu.run_operation(Bit::new(3, ArithmeticTarget8Bit::D), 8),
        0x5B => cpu.run_operation(Bit::new(3, ArithmeticTarget8Bit::E), 8),
        0x5C => cpu.run_operation(Bit::new(3, ArithmeticTarget8Bit::H), 8),
        0x5D => cpu.run_operation(Bit::new(3, ArithmeticTarget8Bit::L), 8),
        0x5E => cpu.run_operation(Bit::new(3, ArithmeticTarget8Bit::HLAddr), 16),
        0x5F => cpu.run_operation(Bit::new(3, ArithmeticTarget8Bit::A), 8),

        0x60 => cpu.run_operation(Bit::new(4, ArithmeticTarget8Bit::B), 8),
        0x61 => cpu.run_operation(Bit::new(4, ArithmeticTarget8Bit::C), 8),
        0x62 => cpu.run_operation(Bit::new(4, ArithmeticTarget8Bit::D), 8),
        0x63 => cpu.run_operation(Bit::new(4, ArithmeticTarget8Bit::E), 8),
        0x64 => cpu.run_operation(Bit::new(4, ArithmeticTarget8Bit::H), 8),
        0x65 => cpu.run_operation(Bit::new(4, ArithmeticTarget8Bit::L), 8),
        0x66 => cpu.run_operation(Bit::new(4, ArithmeticTarget8Bit::HLAddr), 16),
        0x67 => cpu.run_operation(Bit::new(4, ArithmeticTarget8Bit::A), 8),
        0x68 => cpu.run_operation(Bit::new(5, ArithmeticTarget8Bit::B), 8),
        0x69 => cpu.run_operation(Bit::new(5, ArithmeticTarget8Bit::C), 8),
        0x6A => cpu.run_operation(Bit::new(5, ArithmeticTarget8Bit::D), 8),
        0x6B => cpu.run_operation(Bit::new(5, ArithmeticTarget8Bit::E), 8),
        0x6C => cpu.run_operation(Bit::new(5, ArithmeticTarget8Bit::H), 8),
        0x6D => cpu.run_operation(Bit::new(5, ArithmeticTarget8Bit::L), 8),
        0x6E => cpu.run_operation(Bit::new(5, ArithmeticTarget8Bit::HLAddr), 16),
        0x6F => cpu.run_operation(Bit::new(5, ArithmeticTarget8Bit::A), 8),

        0x70 => cpu.run_operation(Bit::new(6, ArithmeticTarget8Bit::B), 8),
        0x71 => cpu.run_operation(Bit::new(6, ArithmeticTarget8Bit::C), 8),
        0x72 => cpu.run_operation(Bit::new(6, ArithmeticTarget8Bit::D), 8),
        0x73 => cpu.run_operation(Bit::new(6, ArithmeticTarget8Bit::E), 8),
        0x74 => cpu.run_operation(Bit::new(6, ArithmeticTarget8Bit::H), 8),
        0x75 => cpu.run_operation(Bit::new(6, ArithmeticTarget8Bit::L), 8),
        0x76 => cpu.run_operation(Bit::new(6, ArithmeticTarget8Bit::HLAddr), 16),
        0x77 => cpu.run_operation(Bit::new(6, ArithmeticTarget8Bit::A), 8),
        0x78 => cpu.run_operation(Bit::new(7, ArithmeticTarget8Bit::B), 8),
        0x79 => cpu.run_operation(Bit::new(7, ArithmeticTarget8Bit::C), 8),
        0x7A => cpu.run_operation(Bit::new(7, ArithmeticTarget8Bit::D), 8),
        0x7B => cpu.run_operation(Bit::new(7, ArithmeticTarget8Bit::E), 8),
        0x7C => cpu.run_operation(Bit::new(7, ArithmeticTarget8Bit::H), 8),
        0x7D => cpu.run_operation(Bit::new(7, ArithmeticTarget8Bit::L), 8),
        0x7E => cpu.run_operation(Bit::new(7, ArithmeticTarget8Bit::HLAddr), 16),
        0x7F => cpu.run_operation(Bit::new(7, ArithmeticTarget8Bit::A), 8),

        0x80 => cpu.run_operation(Res::new(0, ArithmeticTarget8Bit::B), 8),
        0x81 => cpu.run_operation(Res::new(0, ArithmeticTarget8Bit::C), 8),
        0x82 => cpu.run_operation(Res::new(0, ArithmeticTarget8Bit::D), 8),
        0x83 => cpu.run_operation(Res::new(0, ArithmeticTarget8Bit::E), 8),
        0x84 => cpu.run_operation(Res::new(0, ArithmeticTarget8Bit::H), 8),
        0x85 => cpu.run_operation(Res::new(0, ArithmeticTarget8Bit::L), 8),
        0x86 => cpu.run_operation(Res::new(0, ArithmeticTarget8Bit::HLAddr), 16),
        0x87 => cpu.run_operation(Res::new(0, ArithmeticTarget8Bit::A), 8),
        0x88 => cpu.run_operation(Res::new(1, ArithmeticTarget8Bit::B), 8),
        0x89 => cpu.run_operation(Res::new(1, ArithmeticTarget8Bit::C), 8),
        0x8A => cpu.run_operation(Res::new(1, ArithmeticTarget8Bit::D), 8),
        0x8B => cpu.run_operation(Res::new(1, ArithmeticTarget8Bit::E), 8),
        0x8C => cpu.run_operation(Res::new(1, ArithmeticTarget8Bit::H), 8),
        0x8D => cpu.run_operation(Res::new(1, ArithmeticTarget8Bit::L), 8),
        0x8E => cpu.run_operation(Res::new(1, ArithmeticTarget8Bit::HLAddr), 16),
        0x8F => cpu.run_operation(Res::new(1, ArithmeticTarget8Bit::A), 8),

        0x90 => cpu.run_operation(Res::new(2, ArithmeticTarget8Bit::B), 8),
        0x91 => cpu.run_operation(Res::new(2, ArithmeticTarget8Bit::C), 8),
        0x92 => cpu.run_operation(Res::new(2, ArithmeticTarget8Bit::D), 8),
        0x93 => cpu.run_operation(Res::new(2, ArithmeticTarget8Bit::E), 8),
        0x94 => cpu.run_operation(Res::new(2, ArithmeticTarget8Bit::H), 8),
        0x95 => cpu.run_operation(Res::new(2, ArithmeticTarget8Bit::L), 8),
        0x96 => cpu.run_operation(Res::new(2, ArithmeticTarget8Bit::HLAddr), 16),
        0x97 => cpu.run_operation(Res::new(2, ArithmeticTarget8Bit::A), 8),
        0x98 => cpu.run_operation(Res::new(3, ArithmeticTarget8Bit::B), 8),
        0x99 => cpu.run_operation(Res::new(3, ArithmeticTarget8Bit::C), 8),
        0x9A => cpu.run_operation(Res::new(3, ArithmeticTarget8Bit::D), 8),
        0x9B => cpu.run_operation(Res::new(3, ArithmeticTarget8Bit::E), 8),
        0x9C => cpu.run_operation(Res::new(3, ArithmeticTarget8Bit::H), 8),
        0x9D => cpu.run_operation(Res::new(3, ArithmeticTarget8Bit::L), 8),
        0x9E => cpu.run_operation(Res::new(3, ArithmeticTarget8Bit::HLAddr), 16),
        0x9F => cpu.run_operation(Res::new(3, ArithmeticTarget8Bit::A), 8),

        0xA0 => cpu.run_operation(Res::new(4, ArithmeticTarget8Bit::B), 8),
        0xA1 => cpu.run_operation(Res::new(4, ArithmeticTarget8Bit::C), 8),
        0xA2 => cpu.run_operation(Res::new(4, ArithmeticTarget8Bit::D), 8),
        0xA3 => cpu.run_operation(Res::new(4, ArithmeticTarget8Bit::E), 8),
        0xA4 => cpu.run_operation(Res::new(4, ArithmeticTarget8Bit::H), 8),
        0xA5 => cpu.run_operation(Res::new(4, ArithmeticTarget8Bit::L), 8),
        0xA6 => cpu.run_operation(Res::new(4, ArithmeticTarget8Bit::HLAddr), 16),
        0xA7 => cpu.run_operation(Res::new(4, ArithmeticTarget8Bit::A), 8),
        0xA8 => cpu.run_operation(Res::new(5, ArithmeticTarget8Bit::B), 8),
        0xA9 => cpu.run_operation(Res::new(5, ArithmeticTarget8Bit::C), 8),
        0xAA => cpu.run_operation(Res::new(5, ArithmeticTarget8Bit::D), 8),
        0xAB => cpu.run_operation(Res::new(5, ArithmeticTarget8Bit::E), 8),
        0xAC => cpu.run_operation(Res::new(5, ArithmeticTarget8Bit::H), 8),
        0xAD => cpu.run_operation(Res::new(5, ArithmeticTarget8Bit::L), 8),
        0xAE => cpu.run_operation(Res::new(5, ArithmeticTarget8Bit::HLAddr), 16),
        0xAF => cpu.run_operation(Res::new(5, ArithmeticTarget8Bit::A), 8),

        0xB0 => cpu.run_operation(Res::new(6, ArithmeticTarget8Bit::B), 8),
        0xB1 => cpu.run_operation(Res::new(6, ArithmeticTarget8Bit::C), 8),
        0xB2 => cpu.run_operation(Res::new(6, ArithmeticTarget8Bit::D), 8),
        0xB3 => cpu.run_operation(Res::new(6, ArithmeticTarget8Bit::E), 8),
        0xB4 => cpu.run_operation(Res::new(6, ArithmeticTarget8Bit::H), 8),
        0xB5 => cpu.run_operation(Res::new(6, ArithmeticTarget8Bit::L), 8),
        0xB6 => cpu.run_operation(Res::new(6, ArithmeticTarget8Bit::HLAddr), 16),
        0xB7 => cpu.run_operation(Res::new(6, ArithmeticTarget8Bit::A), 8),
        0xB8 => cpu.run_operation(Res::new(7, ArithmeticTarget8Bit::B), 8),
        0xB9 => cpu.run_operation(Res::new(7, ArithmeticTarget8Bit::C), 8),
        0xBA => cpu.run_operation(Res::new(7, ArithmeticTarget8Bit::D), 8),
        0xBB => cpu.run_operation(Res::new(7, ArithmeticTarget8Bit::E), 8),
        0xBC => cpu.run_operation(Res::new(7, ArithmeticTarget8Bit::H), 8),
        0xBD => cpu.run_operation(Res::new(7, ArithmeticTarget8Bit::L), 8),
        0xBE => cpu.run_operation(Res::new(7, ArithmeticTarget8Bit::HLAddr), 16),
        0xBF => cpu.run_operation(Res::new(7, ArithmeticTarget8Bit::A), 8),

        0xC0 => cpu.run_operation(Set::new(0, ArithmeticTarget8Bit::B), 8),
        0xC1 => cpu.run_operation(Set::new(0, ArithmeticTarget8Bit::C), 8),
        0xC2 => cpu.run_operation(Set::new(0, ArithmeticTarget8Bit::D), 8),
        0xC3 => cpu.run_operation(Set::new(0, ArithmeticTarget8Bit::E), 8),
        0xC4 => cpu.run_operation(Set::new(0, ArithmeticTarget8Bit::H), 8),
        0xC5 => cpu.run_operation(Set::new(0, ArithmeticTarget8Bit::L), 8),
        0xC6 => cpu.run_operation(Set::new(0, ArithmeticTarget8Bit::HLAddr), 16),
        0xC7 => cpu.run_operation(Set::new(0, ArithmeticTarget8Bit::A), 8),
        0xC8 => cpu.run_operation(Set::new(1, ArithmeticTarget8Bit::B), 8),
        0xC9 => cpu.run_operation(Set::new(1, ArithmeticTarget8Bit::C), 8),
        0xCA => cpu.run_operation(Set::new(1, ArithmeticTarget8Bit::D), 8),
        0xCB => cpu.run_operation(Set::new(1, ArithmeticTarget8Bit::E), 8),
        0xCC => cpu.run_operation(Set::new(1, ArithmeticTarget8Bit::H), 8),
        0xCD => cpu.run_operation(Set::new(1, ArithmeticTarget8Bit::L), 8),
        0xCE => cpu.run_operation(Set::new(1, ArithmeticTarget8Bit::HLAddr), 16),
        0xCF => cpu.run_operation(Set::new(1, ArithmeticTarget8Bit::A), 8),

        0xD0 => cpu.run_operation(Set::new(2, ArithmeticTarget8Bit::B), 8),
        0xD1 => cpu.run_operation(Set::new(2, ArithmeticTarget8Bit::C), 8),
        0xD2 => cpu.run_operation(Set::new(2, ArithmeticTarget8Bit::D), 8),
        0xD3 => cpu.run_operation(Set::new(2, ArithmeticTarget8Bit::E), 8),
        0xD4 => cpu.run_operation(Set::new(2, ArithmeticTarget8Bit::H), 8),
        0xD5 => cpu.run_operation(Set::new(2, ArithmeticTarget8Bit::L), 8),
        0xD6 => cpu.run_operation(Set::new(2, ArithmeticTarget8Bit::HLAddr), 16),
        0xD7 => cpu.run_operation(Set::new(2, ArithmeticTarget8Bit::A), 8),
        0xD8 => cpu.run_operation(Set::new(3, ArithmeticTarget8Bit::B), 8),
        0xD9 => cpu.run_operation(Set::new(3, ArithmeticTarget8Bit::C), 8),
        0xDA => cpu.run_operation(Set::new(3, ArithmeticTarget8Bit::D), 8),
        0xDB => cpu.run_operation(Set::new(3, ArithmeticTarget8Bit::E), 8),
        0xDC => cpu.run_operation(Set::new(3, ArithmeticTarget8Bit::H), 8),
        0xDD => cpu.run_operation(Set::new(3, ArithmeticTarget8Bit::L), 8),
        0xDE => cpu.run_operation(Set::new(3, ArithmeticTarget8Bit::HLAddr), 16),
        0xDF => cpu.run_operation(Set::new(3, ArithmeticTarget8Bit::A), 8),

        0xE0 => cpu.run_operation(Set::new(4, ArithmeticTarget8Bit::B), 8),
        0xE1 => cpu.run_operation(Set::new(4, ArithmeticTarget8Bit::C), 8),
        0xE2 => cpu.run_operation(Set::new(4, ArithmeticTarget8Bit::D), 8),
        0xE3 => cpu.run_operation(Set::new(4, ArithmeticTarget8Bit::E), 8),
        0xE4 => cpu.run_operation(Set::new(4, ArithmeticTarget8Bit::H), 8),
        0xE5 => cpu.run_operation(Set::new(4, ArithmeticTarget8Bit::L), 8),
        0xE6 => cpu.run_operation(Set::new(4, ArithmeticTarget8Bit::HLAddr), 16),
        0xE7 => cpu.run_operation(Set::new(4, ArithmeticTarget8Bit::A), 8),
        0xE8 => cpu.run_operation(Set::new(5, ArithmeticTarget8Bit::B), 8),
        0xE9 => cpu.run_operation(Set::new(5, ArithmeticTarget8Bit::C), 8),
        0xEA => cpu.run_operation(Set::new(5, ArithmeticTarget8Bit::D), 8),
        0xEB => cpu.run_operation(Set::new(5, ArithmeticTarget8Bit::E), 8),
        0xEC => cpu.run_operation(Set::new(5, ArithmeticTarget8Bit::H), 8),
        0xED => cpu.run_operation(Set::new(5, ArithmeticTarget8Bit::L), 8),
        0xEE => cpu.run_operation(Set::new(5, ArithmeticTarget8Bit::HLAddr), 16),
        0xEF => cpu.run_operation(Set::new(5, ArithmeticTarget8Bit::A), 8),

        0xF0 => cpu.run_operation(Set::new(6, ArithmeticTarget8Bit::B), 8),
        0xF1 => cpu.run_operation(Set::new(6, ArithmeticTarget8Bit::C), 8),
        0xF2 => cpu.run_operation(Set::new(6, ArithmeticTarget8Bit::D), 8),
        0xF3 => cpu.run_operation(Set::new(6, ArithmeticTarget8Bit::E), 8),
        0xF4 => cpu.run_operation(Set::new(6, ArithmeticTarget8Bit::H), 8),
        0xF5 => cpu.run_operation(Set::new(6, ArithmeticTarget8Bit::L), 8),
        0xF6 => cpu.run_operation(Set::new(6, ArithmeticTarget8Bit::HLAddr), 16),
        0xF7 => cpu.run_operation(Set::new(6, ArithmeticTarget8Bit::A), 8),
        0xF8 => cpu.run_operation(Set::new(7, ArithmeticTarget8Bit::B), 8),
        0xF9 => cpu.run_operation(Set::new(7, ArithmeticTarget8Bit::C), 8),
        0xFA => cpu.run_operation(Set::new(7, ArithmeticTarget8Bit::D), 8),
        0xFB => cpu.run_operation(Set::new(7, ArithmeticTarget8Bit::E), 8),
        0xFC => cpu.run_operation(Set::new(7, ArithmeticTarget8Bit::H), 8),
        0xFD => cpu.run_operation(Set::new(7, ArithmeticTarget8Bit::L), 8),
        0xFE => cpu.run_operation(Set::new(7, ArithmeticTarget8Bit::HLAddr), 16),
        0xFF => cpu.run_operation(Set::new(7, ArithmeticTarget8Bit::A), 8),
    }
}
